// <auto-generated />
using System;
using ExpenseTrackerAPI.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTrackerAPI.Models.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220801165338_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExpenseTrackerAPI.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e0db0f7-d7e6-45e6-b969-a27fbef0fbbc"),
                            Description = "Groceries/Baby Needs/Cosmetics/Personal Care",
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("c11e8c27-d856-4230-beb5-6b7623e297f8"),
                            Description = "Cosmetics/Personal Care",
                            Name = "Personal Care"
                        },
                        new
                        {
                            Id = new Guid("a8e65a6d-8dba-4b09-8795-fa0f8fb89d0e"),
                            Description = "Clothes",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("eef9e797-6ee6-440f-8e18-7cac0d8e6bbf"),
                            Description = "Bus/Taxi/Fuel/Insurance/Maintenance/Parking",
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = new Guid("d31a464e-3e0f-407e-8414-260c22a9a316"),
                            Description = "Mortgage/Taxes/Rent/Insurance",
                            Name = "Housing"
                        },
                        new
                        {
                            Id = new Guid("7bb67c1e-49a5-4593-82bf-f39f40289190"),
                            Description = "Phone/Cell phone/Gas/Cable/Internet/Hydro",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = new Guid("d6c9d38c-c139-425b-b17f-fe4ba3e0507f"),
                            Description = "Health care premiums/Specialists/Over-the-counter",
                            Name = "Medical"
                        },
                        new
                        {
                            Id = new Guid("167497b4-d6dc-41ab-9a37-f9c1f21fd765"),
                            Description = "School/Courses/Training/College/University",
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("084dbf00-3182-4e68-b312-a0769fbb9f9e"),
                            Description = "Gaming/Cinema/Attractions/Museums/Restaurants/Cafe",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("9a311b0d-e44b-48c8-9d24-d208fd49247f"),
                            Description = "Netflix/Disney Plus/Amazon Prime/Youtube Premium/Gaming Subscriptions/etc",
                            Name = "Subscriptions"
                        },
                        new
                        {
                            Id = new Guid("17f974db-50fd-43cb-888e-365d399ebf44"),
                            Description = "Uncategorized",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ExpenseTrackerAPI.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.Models.Expense", b =>
                {
                    b.HasOne("ExpenseTrackerAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
